# Exercises (Optional)

These exercises are not required to complete however are good to do for practice. (Not to be submitted on git)

These exercises are a mix of Python and pandas/EDA practice. Most should be no more than a few lines of code! 

In [4]:
import numpy as np

In [2]:
# here is a Python list:

a = [1, 2, 3, 4, 5, 6]

# get a list containing the last 3 elements of a
b = a[-3:]
print(b)

# reverse the list
b = b[::-1]
print(b)

# get a list where each entry in a is squared (so the new list is [1, 4, 9, 16, 25, 36])
squared = [i*i for i in a]
print(squared)

[4, 5, 6]
[6, 5, 4]
[1, 4, 9, 16, 25, 36]


In [5]:
# create a numpy array from this list
b = np.array(a)
print(b)

[1 2 3 4 5 6]


In [6]:
# find the mean of b
b.mean()

3.5

In [7]:
# get a list where each entry in b is squared (so the new numpy array is [1, 4, 9, 16, 25, 36])
# use a different (numpy-specific) approach
np.power(b, 2)

array([ 1,  4,  9, 16, 25, 36], dtype=int32)

In [12]:
# change b from a length-6 list to a 2x3 matrix
mat = np.reshape(b, (2, 3))
print(mat)

[[1 2 3]
 [4 5 6]]


In [11]:
# find the mean value of each row
mat.mean(axis=1)

array([2., 5.])

In [13]:
# find the mean value of each column
mat.mean(axis=0)

array([2.5, 3.5, 4.5])

In [15]:
# find the third column of b
mat[:,2]

array([3, 6])

In [23]:
# load in the "starbucks.csv" dataset
starbucks = np.genfromtxt("starbucks.csv", delimiter = ',', dtype = None, encoding = 'utf-8')
print(starbucks.shape)
print(starbucks)

(243, 18)
[['beverage_category' 'beverage' 'beverage_prep' ... 'calcium' 'iron'
  'caffeine']
 ['coffee' 'brewed coffee' 'Short' ... '0' '0' '175.0']
 ['coffee' 'brewed coffee' 'Tall' ... '0' '0' '260.0']
 ...
 ['frappuccino blended crme' 'vanilla bean (without whipped cream)'
  'Whole Milk' ... '10' '0' '0.0']
 ['frappuccino blended crme' 'vanilla bean (without whipped cream)'
  'Soymilk' ... '10' '6' '0.0']
 ['frappuccino blended crme' 'vanilla bean (without whipped cream)'
  'Grande Nonfat Milk' ... '15' '0' '0.0']]


In [ ]:
# this is nutritional info for starbucks items
# let's see if we can answer some questions

# what is the average # calories across all items?


In [ ]:
# how many different categories of beverages are there?


In [ ]:
# what is the average # calories for each beverage category?


In [ ]:
# what beverage preparation includes the most sugar on average?


In [ ]:
# what is the average % daily value calcium content for each beverage?


In [ ]:
# It's bulking season. What drink should Naitian get so that he maximizes protein but minimizes calories?
# (you can use more than one line for this one)
# there are multiple valid approaches you can take for this (with different answers)
# I know that you want more calories for bulking season but whatever this is MDST, not Michigan Muscle Club okay


In [ ]:
# plot the distribution of the number of calories in drinks using matplotlib


In [ ]:
# plot the same distribution using seaborn. what about a density plot instead?


In [ ]:
# plot calories against total fat using seaborn


In [ ]:
# plot the distribution of calories in Short, Tall, Grande, and Venti drinks
# (you can use multiple lines for this)
# twist: you should also include the Nonfat Milk drinks that also have an associated size.

# you can decide how you want to visualize this. Colors? Small multiples? Density vs histogram?
# the starbucks is your oyster.
